// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace ShortLegStudio
{
	public static class ArrayExtensions
	{
		public static T ChooseOne<T>(this T[] source) {
			var index = UnityEngine.Random.Range (0, source.Length);
			return source[index];
		}
	}
}

